name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello wolrd, I'm learning github actions"
      - name: multiline script
        run: |
          npm -v
          echo "printing npm version"
      - name: python Shell
        run: |
          import platform
          print(platform.processor())
        shell: python
