name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello wolrd, I'm learning github actions"
      - name: multiline script
        run: |
          npm -v
          echo "printing npm version"
      - name: python Shell
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-on-windowa:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: show location from power shell
        run: Get-Location
      - name: show location from bash
        run: pwd
        shell: bash